version: '3.1'
services:

  # first
  zoo1:
    image: zookeeper:3.4
    hostname: zoo1
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
  exp1:
    image: dabealu/zookeeper-exporter
    ports:
      - 8081:8080
    command: --zk-host=zoo1

  # second
  zoo2:
    image: zookeeper:3.4
    hostname: zoo2
    ports:
      - 2182:2181
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=0.0.0.0:2888:3888 server.3=zoo3:2888:3888
  exp2:
    image: dabealu/zookeeper-exporter
    ports:
      - 8082:8080
    command: --zk-host=zoo2

  # third
  zoo3:
    image: zookeeper:3.4
    restart: always
    hostname: zoo3
    ports:
      - 2183:2181
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=0.0.0.0:2888:3888
  exp3:
    image: dabealu/zookeeper-exporter
    ports:
      - 8083:8080
    command: --zk-host=zoo3

  exp123:
    image: dabealu/zookeeper-exporter
    ports:
      - 8084:8080
    command: --zk-list="zoo1:2181,zoo2:2181,zoo3:2181"
